version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./mydata:/var/lib/postgresql/data
  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    ports:
      - "5000:80"
    depends_on:
      - db